### ISSUE TITLE
请教下指标线的问题

### ISSUE THREAD

**Issue by NuonuoLabs** [fujianlian/KLineChart#1]
如果用新加一条数据，addHeaderData，指标线怎么不见了？

**Comment by fujianlian** [comment]
![image](https://user-images.githubusercontent.com/12555302/47481953-c4d00b80-d867-11e8-8bc9-2869388fbe98.png)
addHeaderData的调用每次会先清除掉之前数据，所以出现了这种情况，可以根据自己需求进行调整

**Comment by ForevereBest** [comment]
@1825492258 请问那个指标线怎么做？
