### ISSUE TITLE
单击如何也显示十字指示器？

### ISSUE THREAD

**Issue by akFace** [fujianlian/KLineChart#10]
单击如何也显示十字指示器【长按那个效果】？就是单击一次显示再单击消失

**Comment by fujianlian** [comment]
![image](https://user-images.githubusercontent.com/12555302/50075406-dacfcc00-0219-11e9-92b5-bf70716f7c4e.png)
上图中的commit是采用点击显示效果，可以阅读下源码对比不同，根据自己需求修改

**Comment by akFace** [comment]
这个提交并没有相关代码修改啊 :joy:
![image](https://user-images.githubusercontent.com/22288837/50128456-f5ed1b00-02af-11e9-8b67-1ca677dc9aab.png)

**Comment by fujianlian** [comment]
在这个commit下及之前的版本代码采用的是点击，不是在这个commit改动点击效果

**Comment by VliceZ** [comment]
@kang558 请问解决了吗
