### ISSUE TITLE
请问有能『在ListView 的Item 里面显示，缩小间隔，使得能放下所有数据的方法』吗?

### ISSUE THREAD

**Issue by kakarrot** [fujianlian/KLineChart#3]
如题，或者请教一下修改思路……

**Comment by fujianlian** [comment]
缩小间隔可以通过修改dimems里设置的默认宽度
![image](https://user-images.githubusercontent.com/12555302/47625492-7620bb00-db60-11e8-930f-a270a8285add.png)
或者通过xml配置： app:kc_line_width="4dp"
