### ISSUE TITLE
demo 能多显示几个 5分 10分 一小时图这种的么？

### ISSUE THREAD

**Issue by dicallc** [fujianlian/KLineChart#5]
还有就是如果要做成动态的数据显示应该怎么做呢

**Comment by fujianlian** [comment]
![image](https://user-images.githubusercontent.com/12555302/48242064-5fa61980-e414-11e8-8527-64a5619229f1.png)
切换数据的话如上图所示。
比如切换5分钟，首先请求5分钟的数据，处理赋值给a，更新mAdapter数据，然后调用kChartView刷新方法即可。
多显示几个5分，10分等，相当自己布局，想显示几个就几个，然乎分别对其onClick监听（获取数据—>更新数据—>页面刷新）就可以实现了

**Comment by zhuoCreator** [comment]
有什么方式可以给k线   高开低收  传精度，现在需要不同币   有不同的精度
